name: 'Dependency Submission'
description: 'Submits dependency snapshots'
inputs:
  java-version:
    description: 'Java version'
    required: false
    default: '17'
  java-distro:
    description: 'Java distribution'
    required: false
    default: 'corretto'
  gradle-version:
    description: 'Gradle version'
    default: 8.7
  gh-package-user:
    description: 'Authentication user'
    required: true
  gh-package-token:
    description: 'Authentication token'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distro }}

    # Dependency submission only occurs as part of the post action step so
    # the review must be executed in a separate job.
    - name: Setup Gradle to generate and submit dependency graphs
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ inputs.gradle-version }}
        dependency-graph: generate-and-submit
        dependency-graph-continue-on-failure: false

    - uses: yumemi-inc/gradle-dependency-diff-report@v2
      env:
        GITHUB_DEPENDENCY_GRAPH_ENABLED: false
      with:
        modules: 'app'
        configuration: 'devDebugCompileClasspath'

    - name: Run the usual CI build (dependency-graph will be generated and submitted post-job)
      env:
        GH_PACKAGE_USER: "${{ inputs.gh-package-user }}"
        GH_PACKAGE_TOKEN: "${{ inputs.gh-package-token }}"
      run: ./gradlew build

