name: 'Dependency Submission'
description: 'Submits dependency snapshots'
inputs:
  build-tool:
    description: 'build tool'
    required: true
  java-version:
    description: 'Java version'
    required: false
    default: '17'
  java-distro:
    description: 'Java distribution'
    required: false
    default: 'corretto'
  gradle-version:
    description: 'Gradle version'
    required: false
    default: 8.7
  gh-package-user:
    description: 'Authentication user'
    required: true
  gh-package-token:
    description: 'Authentication token'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Submit gradle dependency submission snapshot'
      if: ${{ inputs.build-tool }} == 'gradle'
      uses: tyro/gh-platform-technology-workflows/vulnerability-prevention/submission/gradle@add-dependency-review
      with:
        java-version: ${{ inputs.java-version }}
        java-distro: ${{ inputs.java-distro }}
        gradle-version: ${{ inputs.gradle-version }}
        gh-package-user: ${{ inputs.gh-package-user }}
        gh-package-token: ${{ inputs.gh-package-token }}
