name: 'Dependency Review'
description: 'Review vulnerabilities for introduced dependencies'
runs:
  using: "composite"
  steps:
    - uses: actions/dependency-review-action@v4
      with:
        retry-on-snapshot-warnings: true
        show-openssf-scorecard: true
        warn-on-openssf-scorecard-level: 3
