name: 'Dependency Review'
description: 'Review vulnerabilities for introduced dependencies'
runs:
  using: "composite"
  runs-on: ubuntu-latest
  needs: dependency-submission
  steps:
    - uses: actions/dependency-review-action@v4
      with:
        comment-summary-in-pr: on-failure
        retry-on-snapshot-warnings: true
        retry-on-snapshot-warnings-timeout: 300
        show-openssf-scorecard: true
        warn-on-openssf-scorecard-level: 3
