name: 'Gradle Dependency Submission'
description: 'Submits dependency snapshots for gradle'
inputs:
  java-version:
    description: 'Java version'
    required: false
  java-distro:
    description: 'Java distribution'
    required: false
  gradle-version:
    description: 'Gradle version'
  gradle-module:
    description: 'Module to generate the dependency diff report for'
    required: false
  gh-package-user:
    description: 'Authentication user'
    required: true
  gh-package-token:
    description: 'Authentication token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distro }}

    # Dependency submission only occurs as part of the post action step so
    # the review must be executed in a separate job.
    - name: Setup Gradle to generate and submit dependency graphs
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ inputs.gradle-version }}
        dependency-graph: generate-and-submit
        dependency-graph-continue-on-failure: false

    - uses: yumemi-inc/gradle-dependency-diff-report@v2
      env:
        GITHUB_DEPENDENCY_GRAPH_ENABLED: 'false'
      with:
        modules: ${{ inputs.gradle-module }}
        configuration: 'devDebugCompileClasspath'

    - name: Run the usual CI build (dependency-graph will be generated and submitted post-job)
      env:
        GH_PACKAGE_USER: "${{ inputs.gh-package-user }}"
        GH_PACKAGE_TOKEN: "${{ inputs.gh-package-token }}"
      shell: bash
      run: ./gradlew build
