name: 'Dependency Review'
on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # See https://github.com/gradle/actions/tree/main/setup-gradle
      - name: Run snapshot action
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit
          dependency-graph-continue-on-failure: false
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha != '' && github.event.pull_request.head.sha || github.sha }}
        with:
          comment-summary-in-pr: on-failure
          retry-on-snapshot-warnings: true
          show-openssf-scorecard-levels: true
          warn-on-openssf-scorecard-level: 3
          base-ref: master
          head-ref: "${{ env.COMMIT_SHA }}"
