name: 'Dependency Review'
on:
  workflow_call:
    inputs:
      build-tool:
        required: true
        type: string
      java-version:
        required: false
        type: string
        default: '17'
      java-distro:
        description: 'Java distribution'
        required: false
        type: string
        default: 'corretto'
      gradle-version:
        description: 'Gradle version'
        required: false
        type: number
        default: 8.7
      swift-version:
        description: 'swift version'
        required: false
        type: string
        default: 'latest'

permissions:
  contents: write
  pull-requests: write

jobs:
  submission:
    runs-on: ubuntu-latest
    steps:
      - uses: tyro/gh-platform-technology-workflows/vulnerability-prevention/submission@add-dependency-review
        with:
          build-tool: ${{ inputs.build-tool }}
          swift-version: ${{ inputs.swift-version }}
          java-version: ${{ inputs.java-version }}
          java-distro: ${{ inputs.java-distro }}
          gradle-version: ${{ inputs.gradle-version }}
          gh-package-user: "${{ secrets.GH_PACKAGE_USER }}"
          gh-package-token: "${{ secrets.GH_PACKAGE_TOKEN }}"
  analysis:
    needs: submission
    runs-on: ubuntu-latest
    steps:
      - uses: tyro/gh-platform-technology-workflows/vulnerability-prevention/review@add-dependency-review

