name: 'Dependency Review'
on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: on-failure
          retry-on-snapshot-warnings: true
          show-openssf-scorecard-levels: true
          warn-on-openssf-scorecard-level: 3
          base_ref: master
          head_ref: "${{ env.COMMIT_SHA }}"
