name: 'Dependency Review'
on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit
          dependency-graph-continue-on-failure: false

      - name: Run the usual CI build (dependency-graph will be generated and submitted post-job)
        env:
          GH_PACKAGE_USER: "${{ secrets.GH_PACKAGE_USER }}"
          GH_PACKAGE_TOKEN: "${{ secrets.GH_PACKAGE_TOKEN }}"
        run: ./gradlew build

      # - name: Generate and submit dependency graph
      #   uses: gradle/actions/dependency-submission@v3

  dependency-review:
    runs-on: ubuntu-latest
    needs: dependency-submission
    steps:
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha != '' && github.event.pull_request.head.sha || github.sha }}
        with:
          comment-summary-in-pr: on-failure
          retry-on-snapshot-warnings: true
          show-openssf-scorecard: true
          warn-on-openssf-scorecard-level: 3
          base-ref: master
          head-ref: "${{ env.COMMIT_SHA }}"
