name: 'Dependency Review'
on:
  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      # See https://github.com/gradle/actions/tree/main/setup-gradle
      - name: Run snapshot action
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit
          dependency-graph-continue-on-failure: false

      - name: Run all checks, disabling dependency graph generation
        env:
          GH_PACKAGE_USER: "${{ secrets.GH_PACKAGE_USER }}"
          GH_PACKAGE_TOKEN: "${{ secrets.GH_PACKAGE_TOKEN }}"
        run: ./gradlew :dependencies

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha != '' && github.event.pull_request.head.sha || github.sha }}
        with:
          comment-summary-in-pr: on-failure
          retry-on-snapshot-warnings: true
          show-openssf-scorecard-levels: true
          warn-on-openssf-scorecard-level: 3
          base-ref: master
          head-ref: "${{ env.COMMIT_SHA }}"
