name: 'Dependency Review'
on:
  workflow_call:
    inputs:
      build-tool:
        required: true
        type: string
      java-version:
        required: false
        type: string
        default: '17'
      java-distro:
        description: 'Java distribution'
        required: false
        type: string
        default: 'corretto'
      gradle-version:
        description: 'Gradle version'
        required: false
        type: number
        default: 8.7
      gradle-module:
        description: 'Module to generate the dependency diff report for'
        required: false
        type: string
        default: 'app'
      gradle-configuration:
        description: 'Classpath to generate the dependency diff report'
        required: false
        type: string
        default: 'devDebugCompileClasspath'

permissions:
  contents: write

jobs:
  submission:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - uses: tyro/gh-platform-technology-workflows/vulnerability-prevention/submission/gradle@main
        if: ${{ inputs.build-tool == 'gradle' }}
        with:
          java-version: ${{ inputs.java-version }}
          java-distro: ${{ inputs.java-distro }}
          gradle-version: ${{ inputs.gradle-version }}
          gradle-module: ${{ inputs.gradle-module }}
          gradle-configuration: ${{ inputs.gradle-configuration }}
          gh-package-user: "${{ secrets.GH_PACKAGE_USER }}"
          gh-package-token: "${{ secrets.GH_PACKAGE_TOKEN }}"

      - uses: tyro/gh-platform-technology-workflows/vulnerability-prevention/submission/swift@main
        if: ${{ inputs.build-tool == 'swift' }}

      - name: 'Checking if NPM dependency submission'
        run: echo 'Skipping as transitive dependencies are discoverable out of box'
        if: ${{ inputs.build-tool == 'npm' }}

  analysis:
    needs: submission
    runs-on: ubuntu-latest
    steps:
      - uses: tyro/gh-platform-technology-workflows/vulnerability-prevention/review@main
